import {
  User,
  Workspace,
  Task,
  FileItem,
  DiscussionPost,
  MeetingNote,
  Approval,
  CalendarEvent,
  NotificationItem,
  AuditEntry,
  SharedNote,
  WorkloadSnapshot,
  Shift,
  Template,
  WhiteboardItem,
  Poll,
  Kudo,
  Decision,
} from './types';

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws-campus-innovation',
  name: 'Campus Innovation Club',
  description: 'A student-led innovation and technology community planning workshops, events, and outreach programs.',
  plan: 'Student Demo Workspace',
  logoText: 'CIC',
};

export const INITIAL_MEMBERS: User[] = [
  {
    id: 'usr-aisha',
    name: 'Aisha Khan',
    role: 'Admin',
    position: 'Club President',
    avatarInitials: 'AK',
    avatarBg: 'bg-indigo-600',
    email: 'aisha.khan@example.com',
    status: 'Online',
    workloadHours: 24,
    openTasksCount: 8,
    completedTasksCount: 14,
    capacityHours: 25,
  },
  {
    id: 'usr-rohan',
    name: 'Rohan Mehta',
    role: 'Member',
    position: 'Technical Lead',
    avatarInitials: 'RM',
    avatarBg: 'bg-blue-600',
    email: 'rohan.mehta@example.com',
    status: 'Focusing',
    workloadHours: 36,
    openTasksCount: 11,
    completedTasksCount: 19,
    capacityHours: 25,
  },
  {
    id: 'usr-priya',
    name: 'Priya Sharma',
    role: 'Member',
    position: 'Events Coordinator',
    avatarInitials: 'PS',
    avatarBg: 'bg-emerald-600',
    email: 'priya.sharma@example.com',
    status: 'In a meeting',
    workloadHours: 31,
    openTasksCount: 9,
    completedTasksCount: 12,
    capacityHours: 25,
  },
  {
    id: 'usr-daniel',
    name: 'Daniel Thomas',
    role: 'Member',
    position: 'Marketing Lead',
    avatarInitials: 'DT',
    avatarBg: 'bg-amber-600',
    email: 'daniel.thomas@example.com',
    status: 'Away',
    workloadHours: 16,
    openTasksCount: 5,
    completedTasksCount: 8,
    capacityHours: 25,
  },
  {
    id: 'usr-meera',
    name: 'Meera Iyer',
    role: 'Viewer',
    position: 'Volunteer Coordinator',
    avatarInitials: 'MI',
    avatarBg: 'bg-purple-600',
    email: 'meera.iyer@example.com',
    status: 'Online',
    workloadHours: 8,
    openTasksCount: 3,
    completedTasksCount: 7,
    capacityHours: 20,
  },
  {
    id: 'usr-arjun',
    name: 'Arjun Rao',
    role: 'Member',
    position: 'Design Lead',
    avatarInitials: 'AR',
    avatarBg: 'bg-rose-600',
    email: 'arjun.rao@example.com',
    status: 'Offline',
    workloadHours: 20,
    openTasksCount: 6,
    completedTasksCount: 10,
    capacityHours: 25,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'Finalize workshop speaker shortlist',
    description: 'Reach out to industry speakers and confirm availability for the AI and cloud infrastructure tracks.',
    status: 'In Progress',
    priority: 'High',
    assigneeId: 'usr-priya',
    assigneeName: 'Priya Sharma',
    assigneeInitials: 'PS',
    dueDate: '2026-09-10',
    commentsCount: 6,
    attachmentsCount: 2,
    label: 'Event Planning',
    progress: 65,
    lastEditedBy: 'Priya Sharma',
    lastEditedAt: '2 hours ago',
    checklist: [
      { id: 'cl-1', text: 'Draft keynote invitations', completed: true },
      { id: 'cl-2', text: 'Confirm accommodation budget', completed: true },
      { id: 'cl-3', text: 'Collect speaker bios and photos', completed: false },
      { id: 'cl-4', text: 'Send calendar invites and tech specs', completed: false },
    ],
    comments: [
      {
        id: 'c-1',
        authorId: 'usr-aisha',
        authorName: 'Aisha Khan',
        authorInitials: 'AK',
        content: 'Auditorium A is confirmed. Can we confirm the primary keynote speaker by Wednesday?',
        createdAt: 'Yesterday at 4:30 PM',
      },
      {
        id: 'c-2',
        authorId: 'usr-priya',
        authorName: 'Priya Sharma',
        authorInitials: 'PS',
        content: 'Yes, Dr. Vasudevan accepted our invitation! Finalizing travel arrangement approval now.',
        createdAt: 'Today at 10:15 AM',
      },
    ],
    attachments: [
      { id: 'att-1', name: 'Speaker_Shortlist_v3.pdf', size: '1.4 MB' },
      { id: 'att-2', name: 'Keynote_Tech_Requirements.docx', size: '420 KB' },
    ],
    history: [
      { id: 'h-1', authorName: 'Priya Sharma', action: 'changed status to In Progress', timestamp: 'Yesterday' },
      { id: 'h-2', authorName: 'Aisha Khan', action: 'updated priority to High', timestamp: '2 days ago' },
    ],
    viewers: ['Rohan Mehta', 'Aisha Khan'],
  },
  {
    id: 'tsk-2',
    title: 'Build member onboarding form',
    description: 'Create multi-step web form capturing student interests, sub-teams, and technical skills.',
    status: 'To Do',
    priority: 'Medium',
    assigneeId: 'usr-rohan',
    assigneeName: 'Rohan Mehta',
    assigneeInitials: 'RM',
    dueDate: '2026-09-12',
    commentsCount: 3,
    attachmentsCount: 1,
    label: 'Operations',
    progress: 30,
    lastEditedBy: 'Rohan Mehta',
    lastEditedAt: 'Yesterday',
    checklist: [
      { id: 'cl-21', text: 'Create student ID validation rule', completed: true },
      { id: 'cl-22', text: 'Hook up webhook to member directory', completed: false },
      { id: 'cl-23', text: 'Write automated welcome email', completed: false },
    ],
    comments: [
      {
        id: 'c-21',
        authorId: 'usr-daniel',
        authorName: 'Daniel Thomas',
        authorInitials: 'DT',
        content: 'Please make sure social media handles are optional fields.',
        createdAt: 'Sep 4, 11:20 AM',
      },
    ],
    attachments: [{ id: 'att-21', name: 'Onboarding_Fields_Spec.md', size: '12 KB' }],
    history: [
      { id: 'h-21', authorName: 'Rohan Mehta', action: 'added 3 checklist items', timestamp: 'Yesterday' },
    ],
  },
  {
    id: 'tsk-3',
    title: 'Design social media campaign',
    description: 'Prepare Instagram carousels, LinkedIn banners, and WhatsApp promotional posters for Demo Day.',
    status: 'In Review',
    priority: 'High',
    assigneeId: 'usr-daniel',
    assigneeName: 'Daniel Thomas',
    assigneeInitials: 'DT',
    dueDate: '2026-09-09',
    commentsCount: 8,
    attachmentsCount: 4,
    label: 'Marketing',
    progress: 85,
    lastEditedBy: 'Daniel Thomas',
    lastEditedAt: '3 hours ago',
    checklist: [
      { id: 'cl-31', text: 'Design 5-slide carousel for IG', completed: true },
      { id: 'cl-32', text: 'Create animated teaser reel', completed: true },
      { id: 'cl-33', text: 'Aisha review brand compliance', completed: false },
    ],
    comments: [
      {
        id: 'c-31',
        authorId: 'usr-arjun',
        authorName: 'Arjun Rao',
        authorInitials: 'AR',
        content: 'Palette looks super clean. The indigo contrast is very sharp.',
        createdAt: 'Today at 9:00 AM',
      },
    ],
    attachments: [
      { id: 'att-31', name: 'DemoDay_Social_Pack.zip', size: '18.2 MB' },
      { id: 'att-32', name: 'Poster_HiRes_Print.pdf', size: '6.5 MB' },
    ],
    history: [
      { id: 'h-31', authorName: 'Daniel Thomas', action: 'moved to In Review', timestamp: '3 hours ago' },
    ],
  },
  {
    id: 'tsk-4',
    title: 'Upload sponsor agreement',
    description: 'Counter-sign legal memorandum of understanding with TechCorp Campus Partner program.',
    status: 'Done',
    priority: 'Medium',
    assigneeId: 'usr-aisha',
    assigneeName: 'Aisha Khan',
    assigneeInitials: 'AK',
    dueDate: '2026-09-05',
    commentsCount: 2,
    attachmentsCount: 1,
    label: 'Sponsorship',
    progress: 100,
    lastEditedBy: 'Aisha Khan',
    lastEditedAt: 'Sep 5, 2026',
    checklist: [
      { id: 'cl-41', text: 'Legal review by faculty advisor', completed: true },
      { id: 'cl-42', text: 'Counter-sign digital copy', completed: true },
      { id: 'cl-43', text: 'Archive in club legal files', completed: true },
    ],
    comments: [
      {
        id: 'c-41',
        authorId: 'usr-aisha',
        authorName: 'Aisha Khan',
        authorInitials: 'AK',
        content: 'Signed and confirmed! Funds will disburse by next week.',
        createdAt: 'Sep 5, 3:15 PM',
      },
    ],
    attachments: [{ id: 'att-41', name: 'TechCorp_Sponsorship_MOU_Signed.pdf', size: '2.3 MB' }],
    history: [
      { id: 'h-41', authorName: 'Aisha Khan', action: 'marked task completed', timestamp: 'Sep 5' },
    ],
  },
  {
    id: 'tsk-5',
    title: 'Prepare workshop feedback survey',
    description: 'Design post-event survey with Net Promoter Score and topic preference metrics for upcoming tracks.',
    status: 'Backlog',
    priority: 'Low',
    assigneeId: 'usr-meera',
    assigneeName: 'Meera Iyer',
    assigneeInitials: 'MI',
    dueDate: '2026-09-18',
    commentsCount: 1,
    attachmentsCount: 0,
    label: 'Research',
    progress: 10,
    lastEditedBy: 'Meera Iyer',
    lastEditedAt: '2 days ago',
    checklist: [
      { id: 'cl-51', text: 'Formulate 5 quantitative rating scales', completed: true },
      { id: 'cl-52', text: 'Set up QR code printables for seat backs', completed: false },
    ],
    comments: [
      {
        id: 'c-51',
        authorId: 'usr-priya',
        authorName: 'Priya Sharma',
        authorInitials: 'PS',
        content: 'We can distribute this directly after the closing keynote.',
        createdAt: 'Sep 3, 5:00 PM',
      },
    ],
    history: [
      { id: 'h-51', authorName: 'Meera Iyer', action: 'created task', timestamp: 'Sep 3' },
    ],
  },
  {
    id: 'tsk-6',
    title: 'Configure event registration page',
    description: 'Implement ticket quota limits, QR check-in ticket generation, and automated confirmation emails.',
    status: 'In Progress',
    priority: 'High',
    assigneeId: 'usr-arjun',
    assigneeName: 'Arjun Rao',
    assigneeInitials: 'AR',
    dueDate: '2026-09-11',
    commentsCount: 5,
    attachmentsCount: 2,
    label: 'Web',
    progress: 55,
    lastEditedBy: 'Arjun Rao',
    lastEditedAt: '5 hours ago',
    checklist: [
      { id: 'cl-61', text: 'Audit mobile viewport responsiveness', completed: true },
      { id: 'cl-62', text: 'Implement 80 attendee cap counter', completed: true },
      { id: 'cl-63', text: 'Generate scannable check-in tokens', completed: false },
    ],
    comments: [
      {
        id: 'c-61',
        authorId: 'usr-rohan',
        authorName: 'Rohan Mehta',
        authorInitials: 'RM',
        content: 'Test registrations look smooth on iOS and Android Safari.',
        createdAt: 'Today at 8:40 AM',
      },
    ],
    attachments: [
      { id: 'att-61', name: 'Registration_Wireframe.png', size: '890 KB' },
    ],
    history: [
      { id: 'h-61', authorName: 'Arjun Rao', action: 'updated progress to 55%', timestamp: '5 hours ago' },
    ],
  },
];

export const INITIAL_FILES: FileItem[] = [
  {
    id: 'f-1',
    name: 'Innovation Workshop Agenda.docx',
    folder: 'Event Planning',
    size: '420 KB',
    sizeBytes: 430080,
    uploadedBy: 'Priya Sharma',
    uploadedDate: '2026-09-04',
    sharedStatus: 'Shared with Team',
    extension: 'docx',
    type: 'doc',
    contentPreview: 'Detailed minute-by-minute rundown of the innovation workshop keynote, hands-on lab, and speaker panels.',
  },
  {
    id: 'f-2',
    name: 'Sponsor Agreement.pdf',
    folder: 'Sponsorship',
    size: '2.4 MB',
    sizeBytes: 2516582,
    uploadedBy: 'Aisha Khan',
    uploadedDate: '2026-09-02',
    sharedStatus: 'Shared with Team',
    extension: 'pdf',
    type: 'pdf',
    contentPreview: 'Official partnership terms, logo placement guidelines, and workshop booth allocation contracts.',
  },
  {
    id: 'f-3',
    name: 'Social Campaign Assets.zip',
    folder: 'Marketing',
    size: '24.8 MB',
    sizeBytes: 26004684,
    uploadedBy: 'Daniel Thomas',
    uploadedDate: '2026-09-05',
    sharedStatus: 'Shared with Team',
    extension: 'zip',
    type: 'archive',
    contentPreview: 'Full bundle containing SVG icons, promotional Instagram carousels, and print-ready poster exports.',
  },
  {
    id: 'f-4',
    name: 'Club Constitution.pdf',
    folder: 'Club Policies',
    size: '1.1 MB',
    sizeBytes: 1153433,
    uploadedBy: 'Aisha Khan',
    uploadedDate: '2026-08-15',
    sharedStatus: 'Shared with Team',
    extension: 'pdf',
    type: 'pdf',
    contentPreview: 'Official bylaws, executive board voting charters, code of ethics, and student governance policies.',
  },
  {
    id: 'f-5',
    name: 'September Event Budget.xlsx',
    folder: 'Event Planning',
    size: '850 KB',
    sizeBytes: 870400,
    uploadedBy: 'Priya Sharma',
    uploadedDate: '2026-09-01',
    sharedStatus: 'Shared with Team',
    extension: 'xlsx',
    type: 'sheet',
    contentPreview: 'Financial expense ledger covering auditorium deposit, catering, badges, speaker honorariums, and mementos.',
  },
  {
    id: 'f-6',
    name: 'Volunteer Roster.csv',
    folder: 'Meeting Materials',
    size: '95 KB',
    sizeBytes: 97280,
    uploadedBy: 'Meera Iyer',
    uploadedDate: '2026-09-04',
    sharedStatus: 'Shared with Team',
    extension: 'csv',
    type: 'data',
    contentPreview: 'Volunteer shifts, contact numbers, assigned desks, and emergency contact details for Demo Day.',
  },
  {
    id: 'f-7',
    name: 'Brand Guidelines.fig',
    folder: 'Design Assets',
    size: '14.2 MB',
    sizeBytes: 14889779,
    uploadedBy: 'Arjun Rao',
    uploadedDate: '2026-08-28',
    sharedStatus: 'Shared with Team',
    extension: 'fig',
    type: 'design',
    contentPreview: 'Typography tokens, color swatches, logo clear-space rules, and presentation slide templates.',
  },
  {
    id: 'f-8',
    name: 'Meeting Recording - September 4.mp4',
    folder: 'Meeting Materials',
    size: '142 MB',
    sizeBytes: 148897792,
    uploadedBy: 'Rohan Mehta',
    uploadedDate: '2026-09-04',
    sharedStatus: 'Shared with Team',
    extension: 'mp4',
    type: 'video',
    contentPreview: '45-minute core team sync recording with audio transcription and screen shares.',
  },
];

export const INITIAL_DISCUSSIONS: DiscussionPost[] = [
  {
    id: 'disc-1',
    title: 'September Innovation Workshop — volunteer briefing',
    content: `Team, our primary innovation workshop is locked in for Saturday, September 20!

We need 12 volunteers across Registration, Stage Management, Tech Support, and Photography. All core coordinators should review the shift schedule by Thursday.

Please click **Acknowledge** below once you have read the duty guidelines.`,
    authorId: 'usr-aisha',
    authorName: 'Aisha Khan',
    authorInitials: 'AK',
    authorPosition: 'Club President',
    type: 'Announcement',
    pinned: true,
    requiresAcknowledgment: true,
    acknowledgedBy: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-meera'],
    repliesCount: 12,
    createdAt: '2026-09-06T09:30:00Z',
    likes: 9,
    userLiked: true,
    comments: [
      {
        id: 'dc-1',
        authorId: 'usr-priya',
        authorName: 'Priya Sharma',
        authorInitials: 'PS',
        authorPosition: 'Events Coordinator',
        content: 'I have scheduled an orientation session for the volunteers this Friday at 4 PM.',
        createdAt: 'Today at 10:14 AM',
        likes: 4,
      },
      {
        id: 'dc-2',
        authorId: 'usr-meera',
        authorName: 'Meera Iyer',
        authorInitials: 'MI',
        authorPosition: 'Volunteer Coordinator',
        content: 'Roster is populated in the Files section! 10 students have already signed up.',
        createdAt: 'Today at 11:05 AM',
        likes: 3,
      },
      {
        id: 'dc-3',
        authorId: 'usr-daniel',
        authorName: 'Daniel Thomas',
        authorInitials: 'DT',
        authorPosition: 'Marketing Lead',
        content: 'Volunteer badges and lanyards are printed and stored in the club cabinet.',
        createdAt: 'Today at 1:20 PM',
        likes: 2,
      },
    ],
    readBy: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-daniel', 'usr-meera'],
  },
  {
    id: 'disc-2',
    title: 'Should we add a beginner Python track?',
    content: 'We noticed around 40% of survey responses asked for hands-on Python fundamentals alongside the cloud architecture session. What do people think about running a parallel 1-hour workshop in Lab 2?',
    authorId: 'usr-rohan',
    authorName: 'Rohan Mehta',
    authorInitials: 'RM',
    authorPosition: 'Technical Lead',
    type: 'Discussion',
    pinned: false,
    requiresAcknowledgment: false,
    acknowledgedBy: [],
    repliesCount: 8,
    createdAt: '2026-09-05T14:15:00Z',
    likes: 6,
    userLiked: false,
    comments: [
      {
        id: 'dc-4',
        authorId: 'usr-aisha',
        authorName: 'Aisha Khan',
        authorInitials: 'AK',
        authorPosition: 'Club President',
        content: 'Great initiative Rohan. As long as we have mentors to staff both rooms simultaneously.',
        createdAt: 'Sep 5, 3:30 PM',
        likes: 3,
      },
      {
        id: 'dc-5',
        authorId: 'usr-arjun',
        authorName: 'Arjun Rao',
        authorInitials: 'AR',
        authorPosition: 'Design Lead',
        content: 'I can prepare custom cheatsheets for Python syntax if this gets approved.',
        createdAt: 'Sep 5, 4:45 PM',
        likes: 5,
      },
    ],
    readBy: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-arjun'],
  },
  {
    id: 'disc-3',
    title: 'Venue confirmation for Demo Day',
    content: 'The campus administration has officially approved our booking for the Library Auditorium with audiovisual gear. Security will open the side doors by 8:00 AM on event day.',
    authorId: 'usr-priya',
    authorName: 'Priya Sharma',
    authorInitials: 'PS',
    authorPosition: 'Events Coordinator',
    type: 'Announcement',
    pinned: false,
    requiresAcknowledgment: false,
    acknowledgedBy: [],
    repliesCount: 5,
    createdAt: '2026-09-04T16:00:00Z',
    likes: 11,
    userLiked: true,
    comments: [
      {
        id: 'dc-6',
        authorId: 'usr-rohan',
        authorName: 'Rohan Mehta',
        authorInitials: 'RM',
        authorPosition: 'Technical Lead',
        content: 'Awesome! We should do an AV test run with projector cables on Wednesday.',
        createdAt: 'Sep 4, 6:15 PM',
        likes: 2,
      },
    ],
    readBy: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-daniel'],
  },
  {
    id: 'disc-4',
    title: 'Ideas for October outreach campaign',
    content: 'Planning our fall recruitment blitz. We could do lightning tech talks in the cafeteria, stickers distribution, and an online capture-the-flag mini contest. Share thoughts!',
    authorId: 'usr-daniel',
    authorName: 'Daniel Thomas',
    authorInitials: 'DT',
    authorPosition: 'Marketing Lead',
    type: 'Discussion',
    pinned: false,
    requiresAcknowledgment: false,
    acknowledgedBy: [],
    repliesCount: 15,
    createdAt: '2026-09-03T11:00:00Z',
    likes: 7,
    comments: [
      {
        id: 'dc-7',
        authorId: 'usr-meera',
        authorName: 'Meera Iyer',
        authorInitials: 'MI',
        authorPosition: 'Volunteer Coordinator',
        content: 'The CTF puzzle booth last year brought in 60 new signups! Strongly vote for that.',
        createdAt: 'Sep 3, 1:20 PM',
        likes: 4,
      },
    ],
    readBy: ['usr-aisha', 'usr-daniel', 'usr-meera'],
  },
];

export const INITIAL_MEETING_NOTES: MeetingNote[] = [
  {
    id: 'mtg-1',
    title: 'Weekly Core Team Sync',
    date: '2026-09-04',
    time: '15:00 - 15:45',
    participants: ['Aisha Khan', 'Rohan Mehta', 'Priya Sharma', 'Daniel Thomas'],
    attendanceStatus: '4/4 present (100%)',
    meetingType: 'Sync',
    agenda: '1. Review workshop milestone timeline\n2. Budget approval status\n3. Registration system demo\n4. Sponsorship disbursements',
    rawNotes: 'Auditorium A booked and confirmed deposit. Rohan demoed ticket QR generation, needs load testing. Priya contacted 4 keynote speakers, Dr. Vasudevan accepted. Daniel finalized social graphics, waiting for Aisha brand review.',
    aiSummary: 'The team reviewed preparation for the September Innovation Workshop. The speaker shortlist is nearly complete, the venue deposit is confirmed, and the registration page needs final testing before launch.',
    keyDecisions: [
      'Use the library auditorium as the primary venue.',
      'Limit the first workshop to 80 participants.',
      'Publish registration by September 8.',
    ],
    actionItems: [
      {
        id: 'act-1',
        title: 'Finalize speaker shortlist',
        ownerId: 'usr-priya',
        ownerName: 'Priya Sharma',
        priority: 'High',
        dueDate: '2026-09-10',
        status: 'In progress',
      },
      {
        id: 'act-2',
        title: 'Test registration form',
        ownerId: 'usr-rohan',
        ownerName: 'Rohan Mehta',
        priority: 'High',
        dueDate: '2026-09-08',
        status: 'Not started',
      },
      {
        id: 'act-3',
        title: 'Prepare social media announcement',
        ownerId: 'usr-daniel',
        ownerName: 'Daniel Thomas',
        priority: 'Medium',
        dueDate: '2026-09-09',
        status: 'In progress',
      },
    ],
    transcriptPreview: '[00:02] Aisha: Welcome everyone. Let us get an update on venue and tickets.\n[00:08] Priya: Library auditorium deposit went through today with college accounting.\n[00:15] Rohan: I capped ticket registrations at 80 so we guarantee seat comfort.\n[00:27] Daniel: Social media pack is ready for Aisha to sign off.',
    status: 'Processed',
    reviewed: true,
  },
  {
    id: 'mtg-2',
    title: 'Innovation Workshop Planning',
    date: '2026-09-02',
    time: '11:00 - 12:00',
    participants: ['Aisha Khan', 'Priya Sharma', 'Meera Iyer', 'Arjun Rao'],
    attendanceStatus: '4/4 present',
    meetingType: 'Planning',
    agenda: 'Logistics, seating arrangement, volunteer training schedule, catering quotes.',
    rawNotes: 'Checked catering package for 80 attendees with coffee break snacks. Agreed on student volunteer badge design with Arjun. Meera confirmed 10 active student volunteers.',
    aiSummary: 'Logistics alignment session. Budget quotes compiled for catering and attendee credentials. Volunteer training scheduled for Friday.',
    keyDecisions: [
      'Approved vegetarian high-tea catering quote.',
      'Selected lanyard design option B with double clip.',
    ],
    actionItems: [
      {
        id: 'act-4',
        title: 'Order volunteer lanyards',
        ownerId: 'usr-arjun',
        ownerName: 'Arjun Rao',
        priority: 'Medium',
        dueDate: '2026-09-07',
        status: 'Completed',
      },
    ],
    transcriptPreview: '[00:05] Priya: Catering quote is ₹6,200 for 100 snack boxes.\n[00:18] Meera: All 10 volunteers have valid college IDs for facility access.',
    status: 'Processed',
    reviewed: true,
  },
  {
    id: 'mtg-3',
    title: 'Sponsorship Review',
    date: '2026-08-30',
    time: '16:00 - 16:30',
    participants: ['Aisha Khan', 'Daniel Thomas', 'Rohan Mehta'],
    attendanceStatus: '3/3 present',
    meetingType: 'Review',
    agenda: 'TechCorp MOU clauses, logo branding benefits, workshop swag sponsorship.',
    rawNotes: 'TechCorp offering ₹50,000 grant plus cloud credits for participants. Need to place their banner at entrance and feature 1 sponsor slot.',
    aiSummary: '',
    keyDecisions: [
      'Accepted TechCorp gold partnership package.',
    ],
    actionItems: [
      {
        id: 'act-5',
        title: 'Send countersigned MOU copy',
        ownerId: 'usr-aisha',
        ownerName: 'Aisha Khan',
        priority: 'High',
        dueDate: '2026-09-05',
        status: 'Completed',
      },
    ],
    transcriptPreview: '[00:03] Aisha: TechCorp agreed to reimburse speaker travel as well.',
    status: 'Draft',
    reviewed: false,
  },
];

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'appr-1',
    title: 'Approve September workshop venue budget',
    type: 'Budget',
    requestedById: 'usr-priya',
    requestedByName: 'Priya Sharma',
    currentStep: 'Club President review',
    status: 'Pending',
    amount: '₹18,500',
    createdAt: '2026-09-04',
    dueDate: '2026-09-08',
    reviewers: ['Aisha Khan', 'Faculty Advisor Dr. Menon'],
    description: 'Advance payment invoice for Library Auditorium lighting, AV technician overtime, and security deposit for Saturday.',
    attachedFiles: ['Auditorium_Booking_Invoice_984.pdf', 'Expense_Breakdown_Spreadsheet.xlsx'],
    steps: [
      { stepNumber: 1, title: 'Events Coordinator Submission', approverName: 'Priya Sharma', status: 'approved', date: 'Sep 4, 10:00 AM' },
      { stepNumber: 2, title: 'Club President review', approverName: 'Aisha Khan', status: 'current' },
      { stepNumber: 3, title: 'Treasurer & Faculty Signoff', approverName: 'Dr. Menon', status: 'pending' },
    ],
    comments: [
      { id: 'apc-1', author: 'Priya Sharma', text: 'College administration requested this signed by Tuesday morning.', time: 'Sep 4, 10:15 AM' },
    ],
  },
  {
    id: 'appr-2',
    title: 'Approve new event poster',
    type: 'Creative',
    requestedById: 'usr-daniel',
    requestedByName: 'Daniel Thomas',
    currentStep: 'Completed',
    status: 'Approved',
    amount: 'Not applicable',
    createdAt: '2026-09-03',
    dueDate: '2026-09-06',
    reviewers: ['Aisha Khan', 'Arjun Rao'],
    description: 'Final print graphic assets for campus pinboards and social media stories.',
    attachedFiles: ['Poster_DemoDay_Final.pdf'],
    steps: [
      { stepNumber: 1, title: 'Marketing Submission', approverName: 'Daniel Thomas', status: 'approved', date: 'Sep 3' },
      { stepNumber: 2, title: 'Design Lead Review', approverName: 'Arjun Rao', status: 'approved', date: 'Sep 4' },
      { stepNumber: 3, title: 'Club President signoff', approverName: 'Aisha Khan', status: 'approved', date: 'Sep 4' },
    ],
  },
  {
    id: 'appr-3',
    title: 'Approve paid design tool subscription',
    type: 'Software',
    requestedById: 'usr-arjun',
    requestedByName: 'Arjun Rao',
    currentStep: 'Rejected',
    status: 'Rejected',
    amount: '₹3,200/mo',
    createdAt: '2026-08-28',
    dueDate: '2026-09-02',
    reviewers: ['Aisha Khan'],
    description: 'Requested Figma Pro team license for 3 student designers.',
    steps: [
      { stepNumber: 1, title: 'Request Submitted', approverName: 'Arjun Rao', status: 'approved', date: 'Aug 28' },
      { stepNumber: 2, title: 'Budget Evaluation', approverName: 'Aisha Khan', status: 'rejected', date: 'Aug 30' },
    ],
    comments: [
      { id: 'apc-2', author: 'Aisha Khan', text: 'We qualified for the official Figma for Education Free Plan! No paid subscription needed.', time: 'Aug 30' },
    ],
  },
  {
    id: 'appr-4',
    title: 'Approve external speaker honorarium',
    type: 'Payment',
    requestedById: 'usr-aisha',
    requestedByName: 'Aisha Khan',
    currentStep: 'Treasurer review',
    status: 'Pending',
    amount: '₹7,500',
    createdAt: '2026-09-05',
    dueDate: '2026-09-12',
    reviewers: ['Club Treasurer', 'Faculty Advisor'],
    description: 'Travel reimbursement and honorarium token for Dr. Vasudevan keynote talk.',
    attachedFiles: ['Speaker_Bank_Details_Confidential.pdf'],
    steps: [
      { stepNumber: 1, title: 'President Authorization', approverName: 'Aisha Khan', status: 'approved', date: 'Sep 5' },
      { stepNumber: 2, title: 'Treasurer review', approverName: 'Student Treasurer', status: 'current' },
    ],
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Weekly Core Team Sync',
    date: '2026-09-04',
    startTime: '15:00',
    endTime: '16:00',
    type: 'meeting',
    requiredAttendees: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-daniel'],
    optionalAttendees: ['usr-meera'],
    location: 'Club Room 302 & Google Meet',
    description: 'Regular sync covering action items, approvals, and marketing metrics.',
  },
  {
    id: 'evt-2',
    title: 'Innovation Workshop',
    date: '2026-09-20',
    startTime: '09:00',
    endTime: '17:00',
    type: 'meeting',
    requiredAttendees: ['usr-aisha', 'usr-rohan', 'usr-priya', 'usr-daniel', 'usr-meera', 'usr-arjun'],
    optionalAttendees: [],
    location: 'Library Auditorium',
    description: 'Annual flagship hands-on cloud development and innovation summit.',
  },
  {
    id: 'evt-3',
    title: 'Speaker confirmation deadline',
    date: '2026-09-10',
    startTime: '18:00',
    endTime: '19:00',
    type: 'deadline',
    requiredAttendees: ['usr-priya', 'usr-aisha'],
    optionalAttendees: [],
    description: 'Final cutoff for all workshop speaker confirmations and slide decks.',
  },
  {
    id: 'evt-4',
    title: 'Social campaign review',
    date: '2026-09-08',
    startTime: '14:00',
    endTime: '15:00',
    type: 'meeting',
    requiredAttendees: ['usr-daniel', 'usr-arjun', 'usr-aisha'],
    optionalAttendees: [],
    location: 'Design Studio & Virtual',
    description: 'Review carousel slides, promotional video cuts, and copy drafts.',
  },
  {
    id: 'evt-5',
    title: 'Volunteer orientation',
    date: '2026-09-12',
    startTime: '16:30',
    endTime: '17:30',
    type: 'meeting',
    requiredAttendees: ['usr-meera', 'usr-priya'],
    optionalAttendees: ['usr-aisha'],
    location: 'Seminar Hall B',
    description: 'Walk volunteers through badge distribution, registration scanning, and ushering.',
  },
  {
    id: 'evt-6',
    title: 'Sponsor meeting',
    date: '2026-09-09',
    startTime: '10:00',
    endTime: '11:00',
    type: 'meeting',
    requiredAttendees: ['usr-aisha', 'usr-daniel'],
    optionalAttendees: [],
    location: 'TechCorp Zoom Bridge',
    description: 'Briefing TechCorp university relations managers on booth setup and tech specs.',
  },
  {
    id: 'evt-7',
    title: 'Registration launch deadline',
    date: '2026-09-08',
    startTime: '12:00',
    endTime: '13:00',
    type: 'deadline',
    requiredAttendees: ['usr-rohan', 'usr-arjun'],
    optionalAttendees: ['usr-aisha'],
    description: 'Open public ticket registration on club portal at exactly noon.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'New Task Assignment',
    message: 'Priya assigned you a task: "Review Auditorium Tech Specifications".',
    type: 'task',
    createdAt: '15 minutes ago',
    read: false,
    actionUrl: 'tasks',
  },
  {
    id: 'notif-2',
    title: 'Approval Request Approved',
    message: 'Your approval request "Approve new event poster" was approved.',
    type: 'approval',
    createdAt: '1 hour ago',
    read: false,
    actionUrl: 'approvals',
  },
  {
    id: 'notif-3',
    title: 'New Comment on Task',
    message: 'Rohan commented on "Configure event registration page".',
    type: 'task',
    createdAt: '3 hours ago',
    read: false,
    actionUrl: 'tasks',
  },
  {
    id: 'notif-4',
    title: 'Upcoming Meeting Alert',
    message: 'The weekly core team sync starts in 30 minutes.',
    type: 'meeting',
    createdAt: '4 hours ago',
    read: true,
    actionUrl: 'calendar',
  },
  {
    id: 'notif-5',
    title: 'Overdue Action Items',
    message: 'You have 2 overdue action items from the Sponsorship Review meeting.',
    type: 'task',
    createdAt: 'Yesterday',
    read: true,
    actionUrl: 'meeting-notes',
  },
  {
    id: 'notif-6',
    title: 'Announcement Acknowledged',
    message: 'Daniel acknowledged your announcement: "September Innovation Workshop — volunteer briefing".',
    type: 'announcement',
    createdAt: 'Yesterday',
    read: true,
    actionUrl: 'discussions',
  },
];

export const INITIAL_AUDIT_LOG: AuditEntry[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-06 11:20:14',
    actor: 'Aisha Khan',
    actorEmail: 'aisha.khan@example.com',
    action: 'Approved request',
    entity: 'Approval',
    entityName: 'Approve new event poster',
    changeSummary: 'Status changed from Pending to Approved',
    diffBefore: 'status: "Pending"',
    diffAfter: 'status: "Approved"',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-06 09:45:00',
    actor: 'Rohan Mehta',
    actorEmail: 'rohan.mehta@example.com',
    action: 'Updated task status',
    entity: 'Task',
    entityName: 'Build member onboarding form',
    changeSummary: 'Moved from Backlog to To Do, added 3 checklist items',
    diffBefore: 'status: "Backlog", checklist: 0',
    diffAfter: 'status: "To Do", checklist: 3',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-05 16:30:22',
    actor: 'Priya Sharma',
    actorEmail: 'priya.sharma@example.com',
    action: 'Uploaded file',
    entity: 'File',
    entityName: 'Speaker shortlist.xlsx',
    changeSummary: 'Uploaded version 2 (850 KB) to Event Planning folder',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-05 14:10:05',
    actor: 'Daniel Thomas',
    actorEmail: 'daniel.thomas@example.com',
    action: 'Edited task details',
    entity: 'Task',
    entityName: 'Design social media campaign',
    changeSummary: 'Updated progress to 85% and uploaded 2 assets',
    diffBefore: 'progress: 60%',
    diffAfter: 'progress: 85%',
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-04 15:05:00',
    actor: 'Aisha Khan',
    actorEmail: 'aisha.khan@example.com',
    action: 'Created meeting notes',
    entity: 'Meeting',
    entityName: 'Weekly Core Team Sync',
    changeSummary: 'Initiated agenda, logged 4 attendees, captured 3 action items',
  },
  {
    id: 'aud-6',
    timestamp: '2026-09-04 11:15:30',
    actor: 'Meera Iyer',
    actorEmail: 'meera.iyer@example.com',
    action: 'Acknowledged announcement',
    entity: 'Discussion',
    entityName: 'September Innovation Workshop — volunteer briefing',
    changeSummary: 'Recorded user acknowledgment timestamp',
  },
  {
    id: 'aud-7',
    timestamp: '2026-09-03 17:00:12',
    actor: 'Arjun Rao',
    actorEmail: 'arjun.rao@example.com',
    action: 'Updated approval item',
    entity: 'Approval',
    entityName: 'Approve new event poster',
    changeSummary: 'Attached final proof document for Aisha signoff',
  },
];

export const INITIAL_SHARED_NOTES: SharedNote[] = [
  {
    id: 'note-1',
    title: 'Club Operations Handbook',
    category: 'Operations',
    content: `# Campus Innovation Club Handbook

Welcome to the operations wiki. This document serves as the authoritative source of truth for all executive leads and team coordinators.

## 1. Meeting Cadence
- **Core Executive Sync**: Every Friday at 3:00 PM
- **Sub-team Standups**: Tuesdays asynchronously via Discussion threads
- **Monthly All-Hands**: First Saturday of every academic month

## 2. Financial Requisitions
All expenses greater than ₹1,000 require an explicit approval request created on CloudOps Workspace. Keep digital GST invoices saved in the \`Sponsorship\` or \`Event Planning\` file folders.

## 3. Communication Etiquette
- High priority alerts must be marked as **Announcement requiring acknowledgment**.
- Routine queries belong in **Discussions**.
`,
    lastEditedBy: 'Aisha Khan',
    lastEditedAt: '2 hours ago',
    isFavorite: true,
    contributors: ['Aisha Khan', 'Rohan Mehta', 'Priya Sharma'],
    activeEditor: 'Rohan Mehta',
    commentsCount: 4,
    relatedTasks: ['tsk-2', 'tsk-4'],
    relatedMeetings: ['mtg-1'],
  },
  {
    id: 'note-2',
    title: 'Event Day Runbook',
    category: 'Events',
    content: `# Event Day Master Runbook

## Timeline: September 20, 2026
- **07:30 AM**: Logistics lead arrival, key collection from library security.
- **08:00 AM**: Audio-Visual check (projector, HDMI switchers, lavalier mics).
- **08:30 AM**: Volunteer briefing in Seminar Hall B.
- **09:00 AM**: Registration desk open; badge scanning commences.
- **09:45 AM**: Seating doors close, introductory club video.
- **10:00 AM**: Keynote address by Dr. Vasudevan.
- **12:30 PM**: Lunch networking & sponsor booth interactions.
- **02:00 PM**: Hands-on Cloud Coding Lab.
- **04:30 PM**: Wrap-up, certificate distribution, and survey QR.
- **05:30 PM**: Venue cleanup & security handover.
`,
    lastEditedBy: 'Priya Sharma',
    lastEditedAt: 'Yesterday',
    isFavorite: true,
    contributors: ['Priya Sharma', 'Meera Iyer', 'Aisha Khan'],
    commentsCount: 7,
    relatedTasks: ['tsk-1', 'tsk-6'],
    relatedMeetings: ['mtg-1', 'mtg-2'],
  },
  {
    id: 'note-3',
    title: 'New Member Onboarding',
    category: 'Operations',
    content: `# Onboarding Playbook for New Leads

1. Add student to CloudOps Workspace with appropriate Member role.
2. Share repository links and Figma design tokens.
3. Schedule an informal 15-minute coffee chat with team lead.
4. Assign first starter issue marked \`good-first-task\`.
`,
    lastEditedBy: 'Rohan Mehta',
    lastEditedAt: '3 days ago',
    isFavorite: false,
    contributors: ['Rohan Mehta', 'Aisha Khan'],
    commentsCount: 2,
    relatedTasks: ['tsk-2'],
  },
  {
    id: 'note-4',
    title: 'Sponsorship Playbook',
    category: 'Finance',
    content: `# Sponsorship Outreach Strategy

### Tier Structure:
- **Title Sponsor (₹50,000)**: Keynote address, main banner, 20 VIP seats, logo on all swag.
- **Track Partner (₹25,000)**: Dedicated challenge track naming rights, booth space.
- **Community Supporter (₹10,000)**: Social media shoutouts and newsletter mention.
`,
    lastEditedBy: 'Daniel Thomas',
    lastEditedAt: 'Sep 1, 2026',
    isFavorite: false,
    contributors: ['Daniel Thomas', 'Aisha Khan'],
    commentsCount: 1,
    relatedTasks: ['tsk-4'],
  },
  {
    id: 'note-5',
    title: 'Social Media Guidelines',
    category: 'Marketing',
    content: `# Brand Voice and Social Guidelines

- **Tone**: Enthusiastic, accessible, builder-first, student-centric.
- **Colors**: Always adhere to the Indigo (#4F46E5) primary palette.
- **Hashtags**: #CampusInnovation #BuildersAssemble #TechOnCampus
- **Approvals**: All static graphics must be reviewed by Design Lead before publishing.
`,
    lastEditedBy: 'Daniel Thomas',
    lastEditedAt: 'Aug 29, 2026',
    isFavorite: false,
    contributors: ['Daniel Thomas', 'Arjun Rao'],
    commentsCount: 3,
    relatedTasks: ['tsk-3'],
  },
];

export const INITIAL_WORKLOAD_SNAPSHOTS: WorkloadSnapshot[] = [
  {
    memberId: 'usr-aisha',
    memberName: 'Aisha Khan',
    role: 'Club President',
    openTasks: 8,
    completedTasks: 14,
    estimatedHours: 24,
    capacityHours: 25,
    status: 'Balanced',
    focusHoursThisWeek: 9.5,
    suggestedAction: 'Optimal workload. Keep delegating administrative reviews.',
  },
  {
    memberId: 'usr-rohan',
    memberName: 'Rohan Mehta',
    role: 'Technical Lead',
    openTasks: 11,
    completedTasks: 19,
    estimatedHours: 36,
    capacityHours: 25,
    status: 'Overloaded',
    focusHoursThisWeek: 14.0,
    suggestedAction: 'Over capacity by 11 hours. Transfer registration form validation to Arjun or Meera.',
  },
  {
    memberId: 'usr-priya',
    memberName: 'Priya Sharma',
    role: 'Events Coordinator',
    openTasks: 9,
    completedTasks: 12,
    estimatedHours: 31,
    capacityHours: 25,
    status: 'Overloaded',
    focusHoursThisWeek: 11.2,
    suggestedAction: 'Over capacity by 6 hours. Offload vendor logistics follow-up to Meera.',
  },
  {
    memberId: 'usr-daniel',
    memberName: 'Daniel Thomas',
    role: 'Marketing Lead',
    openTasks: 5,
    completedTasks: 8,
    estimatedHours: 16,
    capacityHours: 25,
    status: 'Balanced',
    focusHoursThisWeek: 6.0,
    suggestedAction: 'Healthy pacing. Has room for social ad experiment.',
  },
  {
    memberId: 'usr-meera',
    memberName: 'Meera Iyer',
    role: 'Volunteer Coordinator',
    openTasks: 3,
    completedTasks: 7,
    estimatedHours: 8,
    capacityHours: 20,
    status: 'Underutilized',
    focusHoursThisWeek: 4.5,
    suggestedAction: 'Capacity available (+12 hrs). Prime candidate to absorb event logistics and survey tasks.',
  },
  {
    memberId: 'usr-arjun',
    memberName: 'Arjun Rao',
    role: 'Design Lead',
    openTasks: 6,
    completedTasks: 10,
    estimatedHours: 20,
    capacityHours: 25,
    status: 'Balanced',
    focusHoursThisWeek: 8.0,
    suggestedAction: 'Balanced workload. Can assist with frontend UI implementation.',
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shf-1',
    title: 'Registration Desk',
    date: '2026-09-15',
    startTime: '09:00',
    endTime: '11:00',
    location: 'Main Foyer, Library Building',
    assignedMemberIds: ['usr-meera', 'usr-daniel'],
    requiredCount: 2,
    status: 'Covered',
  },
  {
    id: 'shf-2',
    title: 'Venue Setup & AV Cabling',
    date: '2026-09-15',
    startTime: '08:00',
    endTime: '09:30',
    location: 'Library Auditorium Stage',
    assignedMemberIds: ['usr-rohan'],
    requiredCount: 2,
    status: 'Understaffed',
  },
  {
    id: 'shf-3',
    title: 'Help Desk & Student Check-in',
    date: '2026-09-15',
    startTime: '11:00',
    endTime: '13:00',
    location: 'Auditorium Side Entrance',
    assignedMemberIds: ['usr-meera'],
    requiredCount: 2,
    status: 'Understaffed',
  },
  {
    id: 'shf-4',
    title: 'Photography & Event Live-Posting',
    date: '2026-09-15',
    startTime: '13:00',
    endTime: '15:00',
    location: 'Auditorium Floor & Stage',
    assignedMemberIds: ['usr-arjun', 'usr-daniel'],
    requiredCount: 2,
    status: 'Covered',
  },
  {
    id: 'shf-5',
    title: 'Post-Event Cleanup & Return',
    date: '2026-09-15',
    startTime: '16:00',
    endTime: '17:00',
    location: 'All Venues',
    assignedMemberIds: [],
    requiredCount: 3,
    status: 'Open',
  },
];

export const INITIAL_TEMPLATES: Template[] = [
  {
    id: 'tmpl-1',
    name: 'New Event Launch Checklist',
    description: 'Comprehensive 14-point roadmap covering venue reservations, ticketing, design, catering, and post-event debriefs.',
    category: 'Event planning',
    tasksCount: 14,
    createdBy: 'Priya Sharma',
    lastUsed: 'Yesterday',
    contentPreview: ['Reserve campus auditorium', 'Confirm keynote speaker', 'Create marketing teaser', 'Setup ticket quotas', 'Catering order'],
  },
  {
    id: 'tmpl-2',
    name: 'Weekly Team Meeting Agenda',
    description: 'Standard 45-minute sync framework: Wins of the week, blockers, cross-team requests, and 7-day commitments.',
    category: 'Meeting agendas',
    tasksCount: 4,
    createdBy: 'Aisha Khan',
    lastUsed: 'Sep 4, 2026',
    contentPreview: ['Celebration of milestones', 'Active blockers', 'Review metrics & financials', 'Action item assignment'],
  },
  {
    id: 'tmpl-3',
    name: 'Sponsor Approval Request',
    description: 'Formal requisition outline with cost-benefit analysis, deliverables table, and tax invoice attachment slots.',
    category: 'Approval requests',
    tasksCount: 6,
    createdBy: 'Daniel Thomas',
    lastUsed: 'Aug 29, 2026',
    contentPreview: ['Sponsor brand background', 'Package tier chosen', 'Budget allocation plan', 'Approval signoff chain'],
  },
  {
    id: 'tmpl-4',
    name: 'New Member Onboarding',
    description: 'Step-by-step checklist to guide prospective club leads through permissions, repository access, and mentor assignment.',
    category: 'Onboarding',
    tasksCount: 8,
    createdBy: 'Rohan Mehta',
    lastUsed: 'Sep 2, 2026',
    contentPreview: ['Send welcome handbook', 'Invite to CloudOps Workspace', 'Assign introductory task', '1-on-1 mentor sync'],
  },
  {
    id: 'tmpl-5',
    name: 'Social Media Campaign',
    description: 'Multi-channel promotional workflow covering copy drafting, graphic approval, teaser reels, and analytics tracking.',
    category: 'Task lists',
    tasksCount: 7,
    createdBy: 'Daniel Thomas',
    lastUsed: 'Aug 31, 2026',
    contentPreview: ['Draft copy deck', 'Design 3 carousel slides', 'Faculty advisor approval', 'Schedule LinkedIn & IG posts'],
  },
];

export const INITIAL_WHITEBOARD_ITEMS: WhiteboardItem[] = [
  {
    id: 'wb-1',
    type: 'sticky',
    text: '🚀 Workshop Ideas:\n- Cloud Native 101\n- Serverless APIs\n- Container orchestration with Docker',
    color: '#fef08a', // yellow
    x: 60,
    y: 60,
    width: 220,
    height: 180,
    category: 'Ideas',
  },
  {
    id: 'wb-2',
    type: 'sticky',
    text: '🎤 Potential Speakers:\n- Dr. Vasudevan (Cloud AI)\n- Sarah Lin (Alumni @ Stripe)\n- Alex Rivera (Kubernetes)',
    color: '#bbf7d0', // green
    x: 320,
    y: 60,
    width: 220,
    height: 180,
    category: 'Speakers',
  },
  {
    id: 'wb-3',
    type: 'sticky',
    text: '📢 Promotion Channels:\n- College WhatsApp Groups\n- Instagram Stories + Reel\n- Tech Department bulletin boards\n- Club Slack / Discord',
    color: '#fed7aa', // orange
    x: 580,
    y: 60,
    width: 220,
    height: 180,
    category: 'Marketing',
  },
  {
    id: 'wb-4',
    type: 'sticky',
    text: '⚠️ Risks & Blockers:\n- Campus Wi-Fi bandwidth during lab\n- Need backup HDMI adapters\n- Vegetarian snack shortage',
    color: '#fecdd3', // pink/rose
    x: 60,
    y: 280,
    width: 220,
    height: 180,
    category: 'Risks',
  },
  {
    id: 'wb-5',
    type: 'sticky',
    text: '✅ Next Actions:\n1. Audit lab Wi-Fi on Monday\n2. Order snacks by Wednesday\n3. Print 100 QR stickers',
    color: '#bae6fd', // blue
    x: 320,
    y: 280,
    width: 220,
    height: 180,
    category: 'Actions',
  },
];

export const INITIAL_POLLS: Poll[] = [
  {
    id: 'poll-1',
    question: 'Which day should we hold the October hands-on workshop?',
    authorName: 'Priya Sharma',
    createdAt: '2026-09-04',
    endDate: '2026-09-12',
    isAnonymous: false,
    options: [
      { id: 'opt-1', text: 'Saturday, October 10 (Morning)', votes: 14 },
      { id: 'opt-2', text: 'Sunday, October 11 (Afternoon)', votes: 9 },
      { id: 'opt-3', text: 'Friday evening, October 16', votes: 4 },
    ],
    totalVotes: 27,
    userVotedOptionId: 'opt-1',
    isClosed: false,
  },
  {
    id: 'poll-2',
    question: 'Which outreach topic should we prioritize for fall recruiting?',
    authorName: 'Daniel Thomas',
    createdAt: '2026-09-02',
    endDate: '2026-09-09',
    isAnonymous: true,
    options: [
      { id: 'opt-21', text: 'Artificial Intelligence & Large Language Models', votes: 22 },
      { id: 'opt-22', text: 'Full-Stack Web & Cloud Deployment', votes: 16 },
      { id: 'opt-23', text: 'Cybersecurity & Ethical Hacking', votes: 11 },
      { id: 'opt-24', text: 'Open Source Software Contribution', votes: 8 },
    ],
    totalVotes: 57,
    userVotedOptionId: 'opt-21',
    isClosed: false,
  },
  {
    id: 'poll-3',
    question: 'Should we add a beginner Python track running in parallel?',
    authorName: 'Rohan Mehta',
    createdAt: '2026-09-01',
    endDate: '2026-09-06',
    isAnonymous: false,
    options: [
      { id: 'opt-31', text: 'Yes, definitely needed for newcomers', votes: 19 },
      { id: 'opt-32', text: 'No, keep single high-focus cloud track', votes: 5 },
      { id: 'opt-33', text: 'Only if we have 2 more mentors', votes: 12 },
    ],
    totalVotes: 36,
    isClosed: true,
  },
];

export const INITIAL_KUDOS: Kudo[] = [
  {
    id: 'kudo-1',
    fromName: 'Priya Sharma',
    fromRole: 'Events Coordinator',
    toName: 'Rohan Mehta',
    toRole: 'Technical Lead',
    message: 'Huge thank you to Rohan for fixing the registration ticket QR validation flow so quickly late on Thursday!',
    linkedTask: 'Configure event registration page',
    timestamp: 'Yesterday at 5:15 PM',
    reactions: { '❤️': 6, '👏': 8, '🚀': 5 },
    userReacted: ['👏', '🚀'],
  },
  {
    id: 'kudo-2',
    fromName: 'Daniel Thomas',
    fromRole: 'Marketing Lead',
    toName: 'Meera Iyer',
    toRole: 'Volunteer Coordinator',
    message: 'Shoutout to Meera for organizing volunteer responses within 24 hours. The roster is crystal clear and ready to go!',
    linkedTask: 'Prepare workshop feedback survey',
    timestamp: '2 days ago',
    reactions: { '🎉': 7, '🙌': 4 },
    userReacted: ['🎉'],
  },
  {
    id: 'kudo-3',
    fromName: 'Aisha Khan',
    fromRole: 'Club President',
    toName: 'Arjun Rao',
    toRole: 'Design Lead',
    message: 'Arjun knocked it out of the park with the event poster design. The typography and color balance are pure Linear-level craft.',
    linkedTask: 'Design social media campaign',
    timestamp: '3 days ago',
    reactions: { '🔥': 9, '❤️': 6 },
    userReacted: ['🔥'],
  },
  {
    id: 'kudo-4',
    fromName: 'Rohan Mehta',
    fromRole: 'Technical Lead',
    toName: 'Priya Sharma',
    toRole: 'Events Coordinator',
    message: 'Priya has been managing 4 keynote speakers and the auditorium staff with total calm and precision. Super inspiring!',
    linkedTask: 'Finalize workshop speaker shortlist',
    timestamp: 'Sep 3, 2026',
    reactions: { '⭐': 10, '👏': 5 },
  },
];

export const INITIAL_DECISIONS: Decision[] = [
  {
    id: 'dec-1',
    text: 'Use the library auditorium for the September workshop.',
    decidedBy: 'Executive Board',
    date: '2026-09-04',
    sourceMeetingOrDiscussion: 'Weekly Core Team Sync',
    relatedTasks: ['tsk-1', 'tsk-6'],
    status: 'Active',
    context: 'Auditorium provides high-definition projection, seating for up to 120 students, and campus security clearance.',
  },
  {
    id: 'dec-2',
    text: 'Cap workshop attendance at 80 participants.',
    decidedBy: 'Aisha Khan & Rohan Mehta',
    date: '2026-09-04',
    sourceMeetingOrDiscussion: 'Weekly Core Team Sync',
    relatedTasks: ['tsk-6'],
    status: 'Active',
    context: 'Ensures every attendee gets dedicated desk power, stable Wi-Fi, and hands-on mentor support.',
  },
  {
    id: 'dec-3',
    text: 'Use Google Forms & Webhook for initial registration pipeline.',
    decidedBy: 'Rohan Mehta',
    date: '2026-09-02',
    sourceMeetingOrDiscussion: 'Innovation Workshop Planning',
    relatedTasks: ['tsk-2'],
    status: 'Active',
    context: 'Minimizes custom server overhead while validating student university email domains automatically.',
  },
  {
    id: 'dec-4',
    text: 'Publish promotional content one week before the event.',
    decidedBy: 'Daniel Thomas',
    date: '2026-08-30',
    sourceMeetingOrDiscussion: 'Social Campaign Review',
    relatedTasks: ['tsk-3'],
    status: 'Active',
    context: 'Concentrates buzz and prevents early signups from dropping off or forgetting dates.',
  },
];
